name: "Publish To Microsoft Edge Add-ons"

description: "GitHub action for publishing the extension to Microsoft Edge Add-ons"

inputs:
    api_key:
      description: "The Microsoft Edge Add-ons API key."
      required: true
    client_id:
      description: "The Microsoft Edge Add-ons API client ID."
      required: true
    product_id:
      description: "The Microsoft Edge Add-on product ID."
      required: true
    zip_file_name:
      description: "Name of the downloaded zip file."
      required: true

runs:
  using: "composite"
  steps:
    - name: "🔧 Setup"
      uses: actions/setup-node@v4
      with:
        node-version: 20.9.0
    - name: "📦 Install"
      run: yarn --cwd ./.github/actions/publish-to-microsoft-edge-add-ons/ install
      shell: bash
    - name: "🚀 Upload and Publish to Microsoft Edge Add-ons"
      env:
        API_KEY: ${{ inputs.api_key }}
        CLIENT_ID: ${{ inputs.client_id }}
        PRODUCT_ID: ${{ inputs.product_id }}
        ZIP_FILE_NAME: ${{ inputs.zip_file_name }}
      run: yarn --cwd ./.github/actions/publish-to-microsoft-edge-add-ons/ start
      shell: bash
